### ISSUE TITLE
command line option

### ISSUE THREAD

**Issue by mpkuse** [ros-visualization/rqt_rviz#15]
I see that there are three command line options (https://github.com/ros-visualization/rqt_rviz/blob/lunar-devel/scripts/rqt_rviz)
> --hide-menu
> --display-config
> --ogre-log

However I am not able to use it as I launch the rqt_rviz. 

This works:
rqt --standalone rqt_rviz

This does not work:
rqt --standalone rqt_rviz --hide-menu

**Comment by rhaschke** [comment]
For me, the command-line options are considered in general, but the settings stored in the perspective config file seem to take precedence over command-line options. Should be fixed in #17.

**Comment by rhaschke** [comment]
Fixed via #17.
