### ISSUE TITLE
unable to link against pthreads on ubuntu zesty

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-visualization/rqt_rviz#3]
@chapulina; FYI Looks like the jobs on zesty are failing because unable to link against pthreads.
CI: http://build.ros.org/view/Lbin_uZ64/job/Lbin_uZ64__rqt_rviz__ubuntu_zesty_amd64__binary/2/console

**Comment by mikaelarguedas** [comment]
Follow-up of https://github.com/ros-visualization/rqt_rviz/pull/4#discussion_r114362653

Thanks to @dirk-thomas's help we figured out the culprit. `libpyside2-dev` is the package usually pulling `qtbase5-dev`. But it's [not building on Zesty](https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git/+packages) thus not listed in the [rosdep key](https://github.com/ros/rosdistro/blob/b3508ef11a728987765dc88e8ecb7a1cbf7d2a89/rosdep/python.yaml#L2133).
There is an open issue tracking this on [ros_bootstrap_dependencies](https://github.com/ros-infrastructure/ros_bootstrap_dependencies/issues/5).
Thus I think the way to go would be to branch out (hopefully temporarily) and merge #4 on the newly created lunar-devel branch.

Then we will consolidate the branches into a single one once libpyside is fixed upstream and installable on Zesty

**Comment by dirk-thomas** [comment]
Sounds good to me.

**Comment by mikaelarguedas** [comment]
fixed by #4
