### ISSUE TITLE
move back to single master branch

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-visualization/rqt_rviz#5]
This is to remember to move from the lunar specific branch to a single branch for all distros once https://github.com/ros-infrastructure/ros_bootstrap_dependencies/issues/5 is resolved.
See https://github.com/ros-visualization/rqt_rviz/issues/3#issuecomment-298699707 for context

**Comment by mikaelarguedas** [comment]
Status update: 
While we finally got a version of pyside2 and shiboken for zesty (https://github.com/ros-infrastructure/ros_bootstrap_dependencies/issues/5#issuecomment-338821581, it looks like there is only  no python2 support (https://github.com/ros/rosdistro/pull/16216) so we'll need to keep a separated lunar branch for now

**Comment by rhaschke** [comment]
I think this can be closed, as both Indigo and Lunar are EOL.
