### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/rqt_rviz#7]
All of the dependencies for this package are available in Melodic, so it would be great to get it released there.  Thanks in advance!

**Comment by chapulina** [comment]
I *think* I did everything right:

https://github.com/ros/rosdistro/pull/17741

**Comment by chapulina** [comment]
Done https://github.com/ros/rosdistro/pull/17742

**Comment by clalancette** [comment]
Thank you!
